"use client";

import { motion } from "framer-motion";
import { BellOff, AlertTriangle, Zap, Layers, EyeOff } from "lucide-react";
import { SectionBadge } from "@/components/ui/section-badge";
import { GradientCard } from "@/components/ui/gradient-card";

const problems = [
  {
    icon: BellOff,
    title: "Alert Fatigue",
    desc: "Security teams drown in thousands of daily alerts. Most are noise generated by threshold-based rules with zero runtime context.",
  },
  {
    icon: AlertTriangle,
    title: "False Positives",
    desc: "Legacy SIEMs lack behavioral baselines. Benign anomalies trigger escalation, wasting analyst time and eroding trust in tooling.",
  },
  {
    icon: Zap,
    title: "Blind Automation",
    desc: "Automated response without explainability creates risk. Understanding why a decision was made matters more than speed.",
  },
  {
    icon: Layers,
    title: "Operational Complexity",
    desc: "Disjointed agents, scattered logs, and fragmented dashboards make it impossible to maintain a unified security posture.",
  },
  {
    icon: EyeOff,
    title: "Lack of Runtime Context",
    desc: "Static signatures cannot capture the nuance of running workloads. Memory forensics and behavioral telemetry are missing layers.",
  },
];

export function ProblemSection() {
  return (
    <section id="problem" className="relative py-32 px-6">
      <div className="pointer-events-none absolute inset-0 bg-grid opacity-30" />

      <div className="relative mx-auto max-w-7xl">
        <div className="mb-20 max-w-3xl">
          <motion.div
            initial={{ opacity: 0, y: 16 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5 }}
          >
            <SectionBadge>The Challenge</SectionBadge>
            <h2 className="mt-6 text-4xl font-bold leading-tight tracking-tight text-foreground sm:text-5xl">
              The Problem With{" "}
              <span className="text-glow">Traditional Security</span>
            </h2>
            <p className="mt-4 text-lg leading-relaxed text-secondary">
              Modern infrastructure demands observability. Legacy approaches
              rely on static rules, siloed data, and reactive triage — creating
              fatigue, risk, and operational blind spots.
            </p>
          </motion.div>
        </div>

        <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">
          {problems.slice(0, 3).map(({ icon: Icon, title, desc }, i) => (
            <GradientCard key={title} delay={i * 0.1}>
              <div className="mb-4 inline-flex rounded-lg bg-accent/10 p-2.5">
                <Icon className="h-5 w-5 text-accent" />
              </div>
              <h3 className="mb-2 text-base font-semibold text-foreground">{title}</h3>
              <p className="text-sm leading-relaxed text-secondary">{desc}</p>
            </GradientCard>
          ))}
        </div>

        <div className="mt-5 grid gap-5 sm:grid-cols-2">
          {problems.slice(3).map(({ icon: Icon, title, desc }, i) => (
            <GradientCard key={title} delay={(i + 3) * 0.1}>
              <div className="mb-4 inline-flex rounded-lg bg-accent/10 p-2.5">
                <Icon className="h-5 w-5 text-accent" />
              </div>
              <h3 className="mb-2 text-base font-semibold text-foreground">{title}</h3>
              <p className="text-sm leading-relaxed text-secondary">{desc}</p>
            </GradientCard>
          ))}
        </div>
      </div>
    </section>
  );
}
